version: '3'
services:
    server:
        build: server/.
        command: sh runprod.sh
    nginx:
      restart: always
      build: ./server/nginx/
      ports:
        - "80:80"
      links:
        - server
